paths:
  uploads: uploads
  static: ''
collections_config:
  pages:
    path: ''
    icon: wysiwyg
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  archives:
    path: _archives
    icon: archive
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  drafts:
    path: _drafts
    icon: event
    disable_url: false
    _inputs:
      categories:
        type: multiselect
        options:
          allow_create: true
          allow_empty: true
          values: collections.posts[*].categories
        cascade: true
      tags:
        type: multiselect
        options:
          allow_create: true
          allow_empty: true
          values: collections.posts[*].tags
        cascade: true
    create:
      publish_to: posts
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  en_drafts:
    path: en/_drafts
    icon: drafts
    disable_url: false
    _inputs:
      categories:
        type: multiselect
        options:
          allow_create: true
          allow_empty: true
          values: collections.en_posts[*].categories
        cascade: true
      tags:
        type: multiselect
        options:
          allow_create: true
          allow_empty: true
          values: collections.en_posts[*].tags
        cascade: true
    create:
      publish_to: en_posts
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  en_posts:
    path: en/_posts
    icon: compost
    disable_url: false
    _inputs:
      categories:
        type: multiselect
        options:
          allow_create: true
          allow_empty: true
          values: collections.en_posts[*].categories
        cascade: true
      tags:
        type: multiselect
        options:
          allow_create: true
          allow_empty: true
          values: collections.en_posts[*].tags
        cascade: true
    add_options:
      - name: Add Post
      - name: Add Draft
        collection: en_drafts
    create:
      path: >-
        [relative_base_path]/{date|year}-{date|month}-{date|day}-{title|slugify}.[ext]
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  posts:
    path: _posts
    icon: event_available
    disable_url: false
    _inputs:
      categories:
        type: multiselect
        options:
          allow_create: true
          allow_empty: true
          values: collections.posts[*].categories
        cascade: true
      tags:
        type: multiselect
        options:
          allow_create: true
          allow_empty: true
          values: collections.posts[*].tags
        cascade: true
    add_options:
      - name: Add Post
      - name: Add Draft
        collection: drafts
    create:
      path: >-
        [relative_base_path]/{date|year}-{date|month}-{date|day}-{title|slugify}.[ext]
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  biathlon:
    path: biathlon
    icon: ballot
    disable_url: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  data:
    path: _data
    icon: data_usage
    disable_url: true
    disable_add: true
    disable_add_folder: true
    disable_file_actions: true
  en:
    path: en
    icon: ent
    disable_url: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_snippets_imports:
  jekyll: true
timezone: Europe/Zurich
markdown:
  engine: kramdown
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: false
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: true
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: true
    attribute_elements:
      inline: right
      block: below
      tr: none
      td: none
      li: right-of-prefix
