seo:
  site_name: Example
  title: Example SEO Title
  description:
  keywords:
  social_image:
  author:
  favicon_image:
social:
  instagram_url:
  facebook_url:
  pinterest_url:
  linkedin_url:
design:
  dark-text_color: '#665039'
  medium-text_color: '#A57C50'
  light-text_color: '#f7f5f3'
  featured-text_color: '#ff0000'
  dark_color: '#665039'
  medium_color: '#A57C50'
  light_color: '#F0C4C6'
  v-light_color: '#F5F1E0'
  featured_color: '#6495ed'
  accent_color: '#a74a4a'
